### ISSUE TITLE
Jacobian definition

### ISSUE THREAD

**Issue by jebej** [SciML/ParameterizedFunctions.jl#67]
Is the recommended style to define a jacobian still:
```
(p::LotkaVolterra)(::Type{Val{:jac}},t,u,J)
```

It seems, at least for `CVODE_BDF`, that a `jac` field is instead required.

**Comment by YingboMa** [comment]
Nope, we now use ODEFunction.

**Comment by jebej** [comment]
Ok, so if I was using my own Parameterized function type, I need to adopt the ODEFunction interface, and instead subtype `AbstractODEFunction`?

**Comment by YingboMa** [comment]
What’s your use case? You can try to use ModelingToolkit.

On June 1, 2020 at 19:20 GMT, Jérémy <notifications@github.com> wrote:

Ok, so if I was using my own Parameterized function type, I need to adopt the ODEFunction interface, and instead subtype AbstractODEFunction?

**Comment by jebej** [comment]
The usecase is solving a Quantum Liouvillian, where the operators are sparse and complex, and I use the 5-arg `mul!` to have everything in place because I also need to evaluate time-dependent user functions as coefficients for some of the operators (see [here](https://github.com/jebej/Schrodinger.jl/blob/8b6f63a5d8ba4f76f8229b2eed6262aee3e0985b/src/dynamics/liouvillian.jl#L18-L27)).

As far as I can tell, none of the pre-existing solutions work for this, which is why I made my own type.

**Comment by jebej** [comment]
I'd like to talk more about getting this to work if you'd have the time,

w.r.t. this issue, it seems like ParameterizedFunctions are on the way out and that the `(p::LotkaVolterra)(::Type{Val{:jac}},t,u,J)` syntax is not supported anymore. Is that correct?

In case it matters, it would be nice to still support it, for those who like me are using functor types. With functor types, it is impossible to define a function in the `jac` field, because the function would itself depends on the instance of the functor...

**Comment by ChrisRackauckas** [comment]
>w.r.t. this issue, it seems like ParameterizedFunctions are on the way out and that the (p::LotkaVolterra)(::Type{Val{:jac}},t,u,J) syntax is not supported anymore. Is that correct?

Yes, that's been gone for awhile.

>In case it matters, it would be nice to still support it, for those who like me are using functor types. With functor types, it is impossible to define a function in the jac field, because the function would itself depends on the instance of the functor...

You can define an `ODEFunction` and add your own `jac`

>The usecase is solving a Quantum Liouvillian, where the operators are sparse and complex, and I use the 5-arg mul! to have everything in place because I also need to evaluate time-dependent user functions as coefficients for some of the operators (see here).

That's fine with MTK.
