### ISSUE TITLE
Anonymous definition doesn't work :-(

### ISSUE THREAD

**Issue by drozzy** [SciML/ParameterizedFunctions.jl#71]
I'm trying to use ode_def without a name and I'm getting this error:
<img width="1147" alt="Screen Shot 2020-09-26 at 12 01 56 AM" src="https://user-images.githubusercontent.com/140710/94329721-7fed0c00-ff8b-11ea-8f8f-622c5e4da110.png">

Here are my versions:
<img width="449" alt="Screen Shot 2020-09-26 at 12 02 27 AM" src="https://user-images.githubusercontent.com/140710/94329730-92674580-ff8b-11ea-8308-2d8bdf633f3e.png">

**Comment by ChrisRackauckas** [comment]
That was a versioning thing, in the MTK versions this should be all fine.
